NGOCXMHT_Identity/Controllers/MemberUnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NGOCXMHT_Identity.Data;
using NGOCXMHT_Identity.Models.Entities;
using NGOCXMHT_Identity.Models.Process;

namespace VicemMVCIdentity.Controllers
{
    public class MemberUnitController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberUnitController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = nameof(SystemPermissions.MemberUnitView))]
        public async Task<IActionResult> Index()
        {
            return View(await _context.MemberUnit.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var memberUnit = await _context.MemberUnit.FindAsync(id);
            if (memberUnit == null) return NotFound();
            return View(memberUnit);
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitCreate))]
        public IActionResult Create()
        {
            var listMemberUnit = new List<MemberUnit>
            {
                new MemberUnit(1, "Vicem Hạ Long", "Thống Nhất, huyện Hoành Bồ, tỉnh Quảng Ninh", "0203 3699240", "www.ximanghalong.vn"),
                new MemberUnit(2, "Vicem Hoàng Thạch", "Thị trấn Minh Tân - Huyện Kinh Môn - Tỉnh Hải Dương", "0220 3821092", " www.ximanghoangthach.com"),
                new MemberUnit(3, "Vicem Hải Phòng", "Tràng Kênh, Minh Đức, Thủy Nguyên, Hải Phòng", "0225 3875356", "www.ximanghaiphong.com.vn"),
                new MemberUnit(4, "Vicem Sông Thao", "Ninh Dân, Thanh Ba, Phú Thọ", "0210 3663272", "www.ximangsongthao.com"),
                new MemberUnit(5, "Vicem Bút Sơn", "Xã Thanh Sơn, Huyện Kim Bảng, Tỉnh Hà Nam", "0226 3851323", "www.vicembutson.com.vn"),
                new MemberUnit(6, "Vicem Tam Điệp", "Số 27, đường Chi Lăng, xã Quang Sơn, thành phố Tam Điệp, tỉnh Ninh Bình", "0229 3772772", "www.vicemtamdiep.com.vn"),
                new MemberUnit(7, "Vicem Bỉm Sơn", "Phường Ba Đình, Thị xã Bỉm Sơn, Tỉnh Thanh Hóa", "0237 3824242", "www.ximangbimson.com.vn"),
                new MemberUnit(8, "Vicem Hoàng Mai", "Phường Quỳnh Thiện, Thị xã Hoàng Mai, Tỉnh Nghệ An", "0238 866170", "www.ximanghoangmai.com.vn"),
                new MemberUnit(9, "Vicem Hải Vân", "65 Nguyễn Văn Cừ, Quận Liên Triều, Tp.Đà Nẵng", "0236.3842172", "www.haivancement.vn"),
                new MemberUnit(10, "Vicem Hà Tiên 1", "360 Bến Chương Dương, phường Cầu Kho, Quận 1, Tp.Hồ Chí Minh", "028.38 368 363", "https://www.vicemhatien.com.vn/")
            };
            try
            {
                _context.MemberUnit.AddRange(listMemberUnit);
                _context.SaveChanges();
            }
            catch { }
            return View();
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitCreate))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberUnitId,Name,Address,PhoneNumber,WebsiteUrl")] MemberUnit memberUnit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(memberUnit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(memberUnit);
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitEdit))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberUnit = await _context.MemberUnit.FindAsync(id);
            if (memberUnit == null)
            {
                return NotFound();
            }
            return View(memberUnit);
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitEdit))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberUnitId,Name,Address,PhoneNumber,WebsiteUrl")] MemberUnit memberUnit)
        {
            if (id != memberUnit.MemberUnitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(memberUnit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberUnitExists(memberUnit.MemberUnitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(memberUnit);
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitDelete))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberUnit = await _context.MemberUnit
                .FirstOrDefaultAsync(m => m.MemberUnitId == id);
            if (memberUnit == null)
            {
                return NotFound();
            }

            return View(memberUnit);
        }
        [Authorize(Policy = nameof(SystemPermissions.MemberUnitDelete))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var memberUnit = await _context.MemberUnit.FindAsync(id);
            if (memberUnit != null)
            {
                _context.MemberUnit.Remove(memberUnit);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberUnitExists(int id)
        {
            return _context.MemberUnit.Any(e => e.MemberUnitId == id);
        }
    }
}

NGOCXMHT_Identity/Controllers/RoleController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NGOCXMHT_Identity.Models.Process;
using NGOCXMHT_Identity.Models.ViewModels;

namespace NGOCXMHT_Identity.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }   
        [Authorize(Policy = nameof(SystemPermissions.RoleView))]
        public async Task<IActionResult> Index()
        {
            var role = await _roleManager.Roles.ToListAsync();
            return View(role);
        }
         [Authorize(Policy = nameof(SystemPermissions.RoleCreate))]
        public  IActionResult Create()
        {
            return View();
        }
         [Authorize(Policy = nameof(SystemPermissions.RoleCreate))]
        [HttpPost]
           public async Task<IActionResult> Create(string roleName)
        {
            if (!string.IsNullOrEmpty(roleName)){
                var role = new IdentityRole(roleName.Trim());
                await _roleManager.CreateAsync(role);
            }
            return RedirectToAction("Index");
        }
           [Authorize(Policy = nameof(SystemPermissions.RoleEdit))]
            public async Task<IActionResult> Edit(string id)
        {
           var role = await _roleManager.FindByIdAsync(id);
           if (role == null){
            return NotFound();
           }
            return View(role);
        }
   [Authorize(Policy = nameof(SystemPermissions.RoleEdit))]
        [HttpPost]
         public async Task<IActionResult> Edit(string id, string newName)
        {
           var role = await _roleManager.FindByIdAsync(id);
           if (role == null){
            return NotFound();
           }
          role.Name = newName;
          await _roleManager.UpdateAsync(role);
          return RedirectToAction("Index");
        }
           [Authorize(Policy = nameof(SystemPermissions.RoleDelete))]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

         var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }
           [Authorize(Policy = nameof(SystemPermissions.RoleDelete))]
        [HttpPost]
         public async Task<IActionResult> DeleteConfim(string id)
        {
           var role = await _roleManager.FindByIdAsync(id);
           if (role != null){
           await _roleManager.DeleteAsync(role);
           }
      
          return RedirectToAction("Index");
        }

        [Authorize(Policy = nameof(SystemPermissions.AssignClaim))]
        public async Task<IActionResult> AssignClaim(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            { return BadRequest(); }
            var allPermissions = Enum.GetValues(typeof(SystemPermissions)).Cast<SystemPermissions>().Select(p => p.ToString()).ToList();
            var roleClaims = await _roleManager.GetClaimsAsync(role);
            if (roleClaims == null)
            {
                roleClaims = new List<Claim>();
            }
            var model = new RoleClaimVM
            {
                RoleId = role.Id,
                RoleName = role.Name,
                Claims = allPermissions.Select(p => new RoleClaim
                {
                    Type = "Permission",
                    Value = p,
                    Selected = roleClaims.Any(c => c.Type == "Permission" && c.Value == p)
                }).ToList()
            };
            return View(model);
        }
        [Authorize(Policy = nameof(SystemPermissions.AssignClaim))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignClaim(RoleClaimVM model)
        {
            if (!ModelState.IsValid)
            { return View(model); }
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            if (role == null)
            { return BadRequest(); }
            var claims = await _roleManager.GetClaimsAsync(role);
            if (claims == null)
            {
                claims = new List<Claim>();
            }
            foreach (var claim in claims.Where(c => c.Type == "Permission"))
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }
            foreach (var claim in model.Claims.Where(c => c.Selected))
            {
                await _roleManager.AddClaimAsync(role, new Claim(claim.Type, claim.Value));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

NGOCXMHT_Identity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-signin-client_id" content="1034437381109-7uci0scesk90jer970afnmiem46t7rhc.apps.googleusercontent.com">
    <title>@ViewData["Title"] - NGOCXMHT_Identity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NGOCXMHT_Identity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NGOCXMHT_Identity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MemberUnit" asp-action="Index">MemberUnit</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NGOCXMHT_Identity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>